### PR TITLE
Fix audio source toggle behavior

### LINKED ISSUE #44: Toggle stops audio source playback
This is because there is no unpause trait in `AudioSinkPlayback`. When the FMOD event is paused `toggle()` will call `play()` from `AudioSinkPlayback` but this is not sufficient.

### PR DESCRIPTION
**Pull request by GitGhillie**
Fixes #44

### CODE REVIEW

File: src/components/audio_source.rs [hunk 1]
```diff
@@ -54,7 +54,11 @@ impl AudioSinkPlayback for AudioSource {
     }
 
     fn play(&self) {
-        self.event_instance.start().unwrap();
+        if self.event_instance.get_paused().unwrap() {
+            self.event_instance.set_paused(false).unwrap();
+        } else {
+            self.event_instance.start().unwrap();
+        }
```
Comment (Salzian) [inline src/components/audio_source.rs:61]: I guess the if-else is not needed. You can just always set the paused state to false and then start.

Comment (GitGhillie) [reply src/components/audio_source.rs:61]: But the AudioSinkPlayback `toggle` method should resume the audio if it's paused. `toggle` calls the AudioSinkPlayback `play` method when it's currently paused. So if you were to get rid of the if-else you would restart the audio instead of resuming it.

From the Bevy source code:
```rust
    /// Toggles the playback of this sink.
    ///
    /// Will pause if playing, and will be resumed if paused.
    fn toggle(&self) {
        if self.is_paused() {
            self.play();
        } else {
            self.pause();
        }
    }
```
It's a bit of a mismatch between play/start/stop/resume behavior of Bevy Audio and FMOD.
Also they call it `play` when their intention is to resume the audio:
```rust
    /// Resumes playback of a paused sink.
    ///
    /// No effect if not paused.
    fn play(&self);
```
IMO they should just call it `resume` then.

Comment (Salzian) [reply src/components/audio_source.rs:61]: Sorry, I brain farted when writing that comment. You are right.

**Review by Salzian — APPROVED** [review]
Tested it and works as intended.
